module.exports = {
    StatusCodes: {
        BAD_REQUEST: 400,
        UNAUTHORIZED: 401,
        FORBIDDEN: 403,
        NOT_FOUND: 404,
        INTERNAL_SERVER_ERROR: 500,
        CREATED: 201,
        OK: 200,
        CONFLICT: 409,
        STATUSERROR: 0,
        STATUSSUCCESS: 1
    },
    Messages: {
        Name: "Name field is required!",
        Email: "Email field is required!",
        UserId: "User id field is required!",
        PassWord: "Password field is required!",
        TransactionId: "Transaction id field is required!",
        Amount: "Amount field is required!",
        AddAmount: "Amount should not in minus!",
        UserNotExist: "User does not exist with this ID!",
        UserExist: "User already exists with this email!",
        TransactionNotExist: "Transaction not exist with this id!",
        AmountAddedSuccessfully: "Amount added successfully!",
        Error: "Something went wrong!",
        CategoryId: "Category id field is required!",
        BalanceError: "Insufficient balance!",
        TransactionSuccess: "Transaction successful!",
        DataSuccess: "data fetch successful!",
        DeleteSuccess: "Deleted successfully!",
        RegisterSuccess: "User registered successfully!",
        InvalideCredentials: "Invalid email or password!",
        LoginSuccess: "Login successful!",
        UpdateSuccess: "Profile Updated Successfully!",
        ProfileImage: "Profile image required!",
        LogoutSuccess: "Logout successful!",
        LogoutError: "Error during logout!",
        TokenRequired: "Token is required for logout!",
        OldPassword: "Old password field is required!",
        NewPassword: "New password field is required!",
        UserId: "User ID is required.",
        OldPassword: "Old password is required.",
        NewPassword: "New password is required.",
        UserNotFound: "User not found.",
        InvalidPasswordStored: "Invalid password stored for the user.",
        InvalidOldPassword: "The old password is incorrect.",
        PasswordUpdated: "Password updated successfully.",
        INTERNAL_SERVER_ERROR: "An internal server error occurred.",
        EMAIL_SERVICE: "Gmail",
        EMAIL_USER: "partytonight2023@gmail.com",
        EMAIL_PASS: "kpepoavgjoltsguh",
        EMAIL_FROM: "ppratiksha936@gmail.com",
        EMAIL_SUBJECT: "Password Reset Request",
        PASSWORD_LENGTH: 10,
        PASSWORD_CHARSET: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()_+-:{}[]|:,<>,.?/~",
        SALT_ROUNDS: 10,
        TEMPMESG: "Temporary password sent to email!",
        Task: "Task field is required!",
        TaskSuccess: "Task added successfully!",
        TaskId: "Task id field required!",
        TaskExist: "Task not found!",
        TaskUpdateSuccess: "Task edited successfully!",
        StatusUpdateSuccess: "Status updated successfully",
        DataNotFound: "Data not found!",
        KEY: 'akdrhmorjkgzttev',
        IMAGEERROR: "Only .jpeg, .jpg, and .png files are allowed!",
        UPLOADFOlDER: "uploads/",
        VERIFYTOKENERROR: "Access denied. No token provided.",
        VERIFYTOKENERROR2: "Invalid token. Please log in again.",
        VERIFYTOKENERROR3: "Invalid token"
    }

};
